### ISSUE TITLE
Move to device after initializing ReparamModule

### ISSUE THREAD

**Issue by g-simmons** [SsnL/PyTorch-Reparam-Module#6]
Hi there,

Can I do something like the following?

```
net = ... # any network, initialize on CPU
net = ReparamModule(net)
device  = torch.device("cuda")
net = net.to(device)
```

I tried this (using both net.to() and net.module.to()) but after the .to() call, the model.module.device is still "cpu". Let me know if I'm missing something.

**Comment by ssnl** [comment]
I don't think that `nn.Module.device` exists in PyTorch API. Where did you get that?

**Comment by g-simmons** [comment]
Oh you're right 😅. I'm working with a model class from Huggingface Transformers that wraps `nn.Module`, my mistake.

My main question is whether I can use `.to()` on a `ReparamModule` instance the same way I can [use `.to()` on an `nn.Module` instance](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.to) (or an `nn.Module` subclass instance). 

If not, is there another way to move a `ReparamModule` to GPU, or do I need to move the module to the appropriate device before creating the `ReparamModule`?

Here's an example:

```
from torchreparam import ReparamModule
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import torch

model = AutoModelForSequenceClassification.from_pretrained("roberta-base")

print(torch.cuda.is_available())

print(isinstance(model, torch.nn.Module))
print(model.device)

print(isinstance(model.roberta.embeddings.word_embeddings.weight, torch.Tensor))
print(model.roberta.embeddings.word_embeddings.weight.device)

model = ReparamModule(model)
print(model.module.device)
print(model.module.roberta.embeddings.word_embeddings.weight.device)

model = model.to("cuda:0")
print(model.module.device) # I would like for this to be "cuda:0"
print(model.module.roberta.embeddings.word_embeddings.weight.device)  # I would like for this to be "cuda:0"
```

output:
```
True
True
cpu
True
cpu
cpu
cpu
cpu
cpu
cpu
cpu
```

**Comment by ssnl** [comment]
I believe that `.to('cuda:0')` actually moved the parameters to CUDA. If you print `model.flat_param.device`, you should see that.

The reason `model.module.roberta.embeddings.word_embeddings.weight.device` is `cpu` is that, at `ReparamModule(model)`, `ReparamModule` 
1. gathers all parameters into a large flattened parameter vector
2. assigns the attributes in `model` to be **views** of the parameter vector created above.

When you call `reparam_model.to('cuda:0')`, the flattened parameter vector is moved to GPU, while the views are not updated to point to the new parameter vector (which is now on GPU). So they stay pointing to the original CPU parameter vector, and thus have `.device` being `cpu`.

This doesn't affect running the model though, since at running time, the latest parameter vector is used.

However, if you want to make that it shows `cuda` when querying the device (as you did above), the easiest workaround is to call `.to` before wrapping.

**Comment by g-simmons** [comment]
Oh I see, makes sense. Thank you for the explanation!
